<a href="https://colab.research.google.com/github/Shivangi144/Data-science-/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:




  dic={"class":[10,11,12],"student":["ram","siya","rima"]}
  c=10
  s="riya"
  if c in dic["class"]:
    print("class is present")
  else:
    print("class not present")
  if s in dic["student"]:
    print("siya is present")
  else:
    print("siya is not present")
#




class is present
siya is not present


In [ ]:
L=["Shivangi",30,90,"False"]
i=0
for i<len[L]:
print(L[i])
i+=1
print(i,L)

SyntaxError: invalid syntax (3260042849.py, line 3)

In [ ]:

b=80
print(a,b)
print(id(a),id(b))
#
a=40
b=45
a=b
print(a,b)
print(id(a),id(b))
#arithmetic operators
a=80
b=40
print(a+b)
print(a*b)
print(a/b)
print(a//b)
print(a-b)
print(a%b)

#relational operator
c=50
d=86
print(c<=d)
print(c>=d)
print(c==d)
print(c != d)

num1=80
num2=70
print(num1>=num2)
print(num1 != num2)

#assignment operator
b=60
b +=30
print(b)

c=50
c -=45
print(c)
#logical operator
a=26
b=56
print(a and b)
print(a or b)
#
name1="hello"
name2=""
print(name1 and name2)
print(name1 or name2)

a=34
b=100
print(a>50 and b<90)
print(a<60 or b>80)

num1=95
print(not(num1  < 82))
print(not(num1 < 120))

a=[]
b=45
print(a and b)

c=["Shivangi","20"]
d={}
print(c or d)
print(c and d)

print("hello")

num1=80
num2=90
print(num1 and num2)


a=110
b=130
print(a ^ b)
print(a & b)
print(110 >> 130)
print(110 << 130)

c=50
d=45
print(c is d)

num1=30
num2=30
print(num1 is num2)
print(num1 is not num2)
print(id(num1))
print(id(num2))
#
num1=-6
num2=-6
print(num1 ==  num2)
print(num1 is num2)
print(id(num1))
print(id(num2))


30 80
11646280 11647880
45 45
11646760 11646760
120
3200
2.0
2
40
0
True
False
False
True
True
True
90
5
56
26

hello
False
True
True
False
[]
['Shivangi', '20']
{}
hello
90
236
2
0
149724241445212923923884827269978013040640
False
True
False
11646280
11646280
True
False
134931672681936
134931672680944


In [ ]:
#conditional statements
num1=54
num2=62
if num1 > num2:
  print(num1)
else:
  print(num2)
#
#num1=int(input("enter the number:"))
if num1:
  print("number:",num1)
else:
  print("zero")

#if else
age=30
if age > 20:
  print("eligible to vote")
else:
  print("not eligible to vote")

#marks=int(input("enter the marks:"))
#if marks >60 and marks<74:
 #   print("grade is c")
#elif marks>75 and marks<90:
 #   print("grade is b")
#elif marks >90 and marks<100:
    #print("grade is a")
#for
l=[10,20,30,40]

for i in range(4):
   print(l[i])
for i in l:
  print(i)
#while
#num1 = int(input("enter the number:"))
while i < num1:
  print(i)
  i +=1
#list
l=[20,21,22,23,24]
i=0
while i < len(l):
  print(l[i])
  i+=1

#dict
d= {"Name":"Shivangi","age":"20"}
l = d.keys()
print(len(d.keys()))
for i in range(len(d.keys())):
  print(i)

#list
l = [20,[30,50,70]]
for i in range(len(l[1])):
  print(l[1])

#break keyword
for i in range(5):
  if i == 2:
    break
 # print(i)
# continue
i = 0
while True:
  if  i == 5:
    break
  else:
    i += 1
    continue



62
number: 54
eligible to vote
10
20
30
40
10
20
30
40
40
41
42
43
44
45
46
47
48
49
50
51
52
53
20
21
22
23
24
2
0
fatal: not a git repository (or any of the parent directories): .git
1
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[30, 50, 70]
[30, 50, 70]
[30, 50, 70]


In [ ]:
!git add .
!git commit -m "Updated notebook"
!git push


fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git


In [ ]:
d = {"Name":" Shivangi","age":"20"}
d.update ({"Name":"Arya mains"})
d['Name'] = "Arya mains new"
print(['age'])
l=[20,50]
print(l[0])
#

d = {"address":{"address1":{"city":"jhotwara","district":"jaipur"},
                "address2":{"city":"choti chaupar","district":"jaipur"}}}

print(d["address"]["address1"]["city"])
print(d["address"]["address1"]["district"])
print(d["address"]["address2"]["city"])
print(d["address"]["address2"]["district"])


#
l = [30,40,60,["hello","hello1",[True,False]]]
print(l)
l1 = l[:3]
print(l1)
l2 = l[:2]
print(l2)
l1 =  l[-1:2]
print(l1)
print(l[3:4:1])
print(l[3][2][-1])

#function
def square(s):
  return s*s
  #map argument
l = [30,60,90,120]
l1 = list(map(square,l))
print(l1)
#map
l1= list(map(lambda x:x*x,l))
print(l1)
#without in built function
l1 =[]
for i in range(3):
  l1.append(l[i] * l[i])
print(l1)
#filter
def hello(x):
  return x.endswith("s")
l = ["mango","litchies","cats","dogs"]
l1 = list(filter(hello,l))
print(l1)
#example1
l1 = []
for i in l:
  if 's' == i[-1]:
    l1.append(i)
print(l1)
#upper
upper_words= list(map(str.upper,l))
print(upper_words)
















['age']
20
jhotwara
jaipur
choti chaupar
jaipur
[30, 40, 60, ['hello', 'hello1', [True, False]]]
[30, 40, 60]
[30, 40]
[]
[['hello', 'hello1', [True, False]]]
False
[900, 3600, 8100, 14400]
[900, 3600, 8100, 14400]
[900, 3600, 8100]
['litchies', 'cats', 'dogs']
['litchies', 'cats', 'dogs']
['MANGO', 'LITCHIES', 'CATS', 'DOGS']


In [ ]:
#try except
try:
    num1 = 60
    num2 = 12
    print (num1/num2)
except:
    print("hello except")

#try except
try:
    num1 = 10
    num2 = 0
    print (num1/num2)
except:
    print("hello except")

#try except and final

try:
    a =10
    b = 5
    print(a/b)
except:
    print("hello except")
finally:
    print("hello finally divide")


5.0
hello except
2.0
hello finally divide


In [ ]:
#import module
import math
print(math.factorial(8))
print(math.pow(9,6))
print(math.pi)

#import example
import math as shivangi
print(shivangi.pow(5,8))
print(shivangi.factorial(9))
print(shivangi.pi)
print(shivangi.floor(87.8578))

#example 2
from math import factorial,pi
print(factorial(8))
print(pi)

#example 3
from math import *
print(floor(16.90))
print(pow(6,3))







40320
531441.0
3.141592653589793
390625.0
362880
3.141592653589793
87
40320
3.141592653589793
16
216.0


In [ ]:
# example
class shivangi:
  def __init__(self,name):
    self.name = name
  def show(self):
    print(self.name)

s = shivangi("hello")
s.show()

#example1
class Shivangi:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def getage(self):
        print("My age is:", self.age)

    def get_name(self):
        print("My name is:", self.name)


s = Shivangi("hello", 20)

s.getage()
s.get_name()
#examplee2
class college:
    def __init__(self, name):
        self.name = name['name']
        self.location = name["location"]
    def getCollege(self):
        print("The college name is: ", self.name)
        print("The college location is: ", self.location)
c = college({"name": "Grras", "location": "Nagpur"})
c.getCollege()

#example
class student:
  def __init__(self , *args):
        self.data = args

  def user(self):
        for i in self.data[0]:
            print(i)

  def details(self):
        for i in self.data[1]:
            print(i ,":" ,self.data[1][i])

s = student(["Shivangi","Rima","Roy"],{"address:":"Riico","college:":"Arya","location:":"Jaipur"})
s.user()
s.details()

#example
class address:
  def __init__(self,city,state):
    self.city=city
    self.state=state
a = address("Nainital","Uttarakahnd")
print(a.state)
print(a.city)



hello
My age is: 20
My name is: hello
The college name is:  Grras
The college location is:  Nagpur
Shivangi
Rima
Roy
address: : Riico
college: : Arya
location: : Jaipur
Uttarakahnd
Nainital


In [ ]:
#Class method and self
class Address:
  def __init__(self,city,state):
    self.city = city
    self.state = state
  def show(self):
    print("the city is:",self.city)
a = Address("Jaipur","Rajasthan") # a->object
a.show()






the city is: Jaipur


In [ ]:
# Inheritance
class Address:
  def __init__(self,city,state):
    self.city = city
    self.state = state
  def location(self):
    return f"my location is {self.city} in {self.state}"
class User(Address):
  def __init__(self,name,age,city,state):
    self.name = name
    self.age = age
    self.city = city
    self.state= state
  def userName(self):
    print(f"My name is {self.name} and my location is {self.city} , {self.state}")
    print(f"My age is {self.age}")
u = User("Shivangi",20,"Jaipur","Rajasthan")
print(u.city)
print(u.state)
u.userName()

a = Address("Jaipur","Rajasthan")






Jaipur
Rajasthan
My name is Shivangi and my location is Jaipur , Rajasthan
My age is 20


Encapsulation

In [ ]:
class Address:
  def __init__(self,city,state):
    self.city = city
    self.state = state
  def location(self):
    print(f"my location is {self.city} , {self.state}")
a = Address("Pithoragarh","Uttarakhand")
a.location()
print(a.city)
print(a.state)


my location is Pithoragarh , Uttarakhand
Pithoragarh
Uttarakhand


Polymorphism

In [ ]:
class Address:
  def __init__(self,city,state):
    self.city = city
    self.state = state
  def location(self):
    print(f" my address is {self.city}, {self.state}")
class Hometown:
  def __init__(self,city,state):
    self.city = city
    self.state = state
  def location(self):
    print(f"my home town location is {self.city},{self.state}")
a = Address("Jaipur","Rajasthan")
a.location()
b = Hometown("Pithoragarh","Uttarakhand")
b.location()



 my address is Jaipur, Rajasthan
my home town location is Pithoragarh,Uttarakahnd


Class variable

In [ ]:
from os import name
class Address:
  total = 10 #class variable
  def __init__(self,city,state):
    self.city = city
    self.state = state
    Address.total +=1
  def location(self):
    print("location")
a = Address("Jaipur","Rajasthan")
b = Address("Sirohi","Rajasthan")
c = Address("Almora","Uttarakhand")
d = Address("Ranikhet","Uttarakhand")
a.total

#overriding
class Address:
  def __init__(self,city,state):
    self.city = city
    self.state = state
  def location(self):
    print("address")
class User(Address):
  def __init__(self,name,age,city,state):
    super().__init__(city,state)
    self.name = name
    self.age = age
  def location(self):
    print("location is ")
u = User("Shivangi",20,"Jaipur","Rajasthan")
u.location()



location is 


Tuple

In [ ]:
#immutable
t = (20,30,40)
print(t[0])
print(t[-1])

#example
marks = [96,92,85]



20
40


In [ ]:
import numpy
print("Have a nice day")
#
import numpy
n = numpy.arange(12)
d = n.reshape(3,4)
print(type(d))
print(d)

#list 1d
l = [3,6,8]
print(l)

#arr 1d
import numpy as np
arr = np.array(l)
print(arr)


#2d list
l = [[2,3,4],[5,6,7]]
l[0][2] = 100
print(l)
#2d array
import numpy as np
arr = np.array([[2,3,4],[5,6,7]])
arr[0][2] = 100
print(arr)







Have a nice day
<class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[3, 6, 8]
[3 6 8]
[[2, 3, 100], [5, 6, 7]]
[[  2   3 100]
 [  5   6   7]]


list vs numpy array

In [ ]:
#list
l = [3,4,5]
lm = l * 2
print(lm)

#array
import numpy as np
arr = np.array(l)
arrM = arr * 2
print(arrM)

#comparison in list
import time
start = time.time()
l = [i*2 for i in range(1000000)]
print("list output",time.time() - start)

#array
import numpy as np
start = time.time()
arr = np.array(1000000) * 2
print("array output",time.time() - start)

#
import numpy as np
arr = np.zeros(8)
print(arr)
#2d
arr = np.zeros((3,4))
print(arr)

#ones
import numpy as np
arr = np.ones(6)
print(arr)

#2d
arr = np.ones((5,6))
print(arr)

#
import numpy as np
arr = np.zeros((3,3))
print(arr + 10)
arr1 = np.ones((2,3))
print(arr1)
#
arr2 = np.ones((4,4))
arr2 = arr2*5
print(arr2)

#
arr = np.zeros((3,5)) + 6
print(arr)

arr1 = np.full((3,2),1)
print(arr1)

#random
import numpy as np
arr = np.random.random(3)
print(arr)

arr1 = np.random.random((3,2))
print(arr1)

#arange for 1d
arr1 = np.arange(4)
print(arr1)

#arange for 2d
arr2 = np.arange(2,3)
print(arr2)

#vector for 1d
import numpy as np
v = np.array([3,4,5])
print(v)

v1 = np.array([[4,5,6],[7,8,9]])
print(v1)

#matrix for 2d list
l = [[10,20,30],[40,50,60]]
print(l)

#2d array
arr = np.array(l)
print(arr)

#tensor
l = [[[30,40],[42,46]],[[50,56],[60,68]]]
print(l)

#array
arr1 = np.array(l)
print(arr1)


#array
import numpy as np
arr = np.array(l)
print("shape:",np.shape)
print("shape",np.shape(arr))
print("dimension:",np.ndim(arr))
print("size",np.size(arr))
print("datatype:",arr.dtype)


[3, 4, 5, 3, 4, 5]
[ 6  8 10]
list output 0.06089925765991211
array output 0.00012302398681640625
[0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
[[1 1]
 [1 1]
 [1 1]]
[0.22220678 0.48367134 0.60647764]
[[0.72305249 0.14225883]
 [0.67019878 0.35924328]
 [0.50949625 0.7657688 ]]
[0 1 2 3]
[2]
[3 4 5]
[[4 5 6]
 [7 8 9]]
[[10, 20, 30], [40, 50, 60]]
[[10 20 30]
 [40 50 60]]
[[[30, 40], [42, 46]], [[50, 56], [60, 68]]]
[[[30 40]
  [42 46]]

 [[50 56]
  [60 68]]]
shape: <function shape at 0x7a340a732660>
shape (2, 2, 2)
dimension: 3
size 8
datatype: int64


In [ ]:
#Reshape array
import numpy as np
arr = np.arange(12)
up_arr = np.reshape(arr,(4,3))
print(up_arr)

#
import numpy as np
arr1 = np.arange(16)
up_arr1 = np.reshape(arr1,(4,4))
print(up_arr1)

#2d
import numpy as np
arr1 = np.arange(18)
up_arr1 = np.reshape(arr1,(3,6))
print(up_arr1)


#flatten
import numpy as np
arr = np.arange(16).reshape((4,4))
print(arr)
up_arr = arr.flatten()
print(up_arr)
print(arr)

#3d
import numpy as np
arr = np.arange(24).reshape(3,4,2)
print(arr)
up_arr = arr.flatten()
print(up_arr)
print(arr)

#3d
import numpy as np
arr = np.arange(48).reshape(2,6,4)
print(arr)
up_arr = arr.flatten()
print(up_arr)
print(arr)

#ravel - works on og array
import numpy as np
#2d
arr = np.arange(20).reshape(4,5)
print(arr)
up_arr = arr.ravel()
print(up_arr)

#3d
arr = np.arange(48).reshape(2,4,6)
print(arr)
up_arr = arr.ravel()
print(up_arr)
print(arr)

#transpose -
import numpy as np
arr = np.arange(12).reshape(4,3)
print(arr)
up_arr = arr.T
print(up_arr)

#3d
import numpy as np
arr = np.arange(36).reshape(4,3,3)
print(arr)
up_arr = arr.T
print(up_arr)

#Slicing
import numpy as np
arr = np.arange(16)
print(arr)
up_arr = arr[:4]
print(up_arr)

#2d
arr1 = np.arange(18).reshape(3,6)
print(arr1)
up_arr1 = arr[:5]
print(up_arr1)

#3d
arr2 = np.arange(48).reshape(6,2,4)
print(arr2)
up_arr2 = arr2[:12]
print(up_arr2)

#
arr1 = np.arange(24).reshape(6,2,2)
print(arr1)
up_arr1 = arr1[0:4,0:2,0:4]
print(arr1[0,0,0])
print(arr1[1,1,1])

#for loop
#1d
import numpy as np
arr = np.arange(16)
print(arr)
for i in range(len(arr)):
    print(arr[i],end = " ")
    i +=1
#2d
arr1 = np.arange(18).reshape(3,6)
for i in arr1:
    for j in i:
      print(j,end = " ")

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 4

KeyboardInterrupt: 

Sorting

In [ ]:
#sort() - 1d
import numpy as np
arr = np.array([54,58,48,93,96,95,32])
print(arr)
arr_s = np.sort(arr)
print(arr_s)

#2d
import numpy as np
arr1 = np.array([[89,56,48],[98,76,78]])
print(arr1)
arr1_s = np.sort(arr1,)
print(arr1_s)

#3d
import numpy as np
arr2 = np.array([[[85,36],[46,32]],[[92,81],[94,98]]])
print(arr2)
arr2_s = np.sort(arr2)
print(arr2_s)

#
import numpy as np
arr = np.array([68,90,93,86,45,50])
print(arr)
desc_arr = np.sort(arr)[::-1]
print(desc_arr)

#Filter
import numpy as np
arr = np.array([50,59,90,80,92])
print(arr)
arr_f = arr[arr > 50]
print(arr_f)

#2d
import numpy as np
arr1 = np.array([[78,80,90],[65,29,54]])
print(arr1)
arr1_f = arr[arr < 80 ]
print(arr1_f)

#Fancy indexing
import numpy as np
arr = np.array([25,85,98,26,20,86])
print(arr)
arr_f = arr[[0,4]]
print(arr_f)

#2d
arr1 = np.array([[35,78,74],[89,70,48],[89,91,87]])
print(arr1)
arr1_f = (arr1[:,[0,2]])
print(arr1_f)

#np.where
import numpy as np
arr = np.array([10,55,75,79,99])
print(arr)
arr_w = np.where(arr > 40,"True","False" )
print(arr_w)

#
arr1 = np.array([63,76,72,29,90,98,95])
print(arr1)
result = np.where(arr1 >= 76, "Grade A","Grade B" )
print(result)
remainder = np.where(arr1 % 2 == 1,"prime","not prime")
print(remainder)

#concatenate
import numpy as np
arr = np.array([45,49,52])
arr1 = np.array([80,52,100])
arr_arr1 = np.concatenate((arr,arr1))
print(arr_arr1)

#2d
arr2 = np.array([[76,56,90],[88,51,8]])
arr3 = np.array([[78,102,98],[75,35,48]])
arr2_arr3 = np.concatenate((arr2,arr3))
print(arr2_arr3)

#Stastical functions
arr = np.array([69,61,46,100,120])
print(arr)
sum = np.sum(arr)
print(sum)
mean = np.mean(arr)
print(mean)
print("median:",np.median(arr))
print("max:",np.max(arr))
print("cumulative",np.cumprod(arr))
print("product",np.prod(arr))
print("range:",np.ptp(arr))
print("deviation:",np.std(arr))
print("unique",np.unique(arr))
print("percentile",np.percentile(arr,100))
print("variance",np.var(arr))



[54 58 48 93 96 95 32]
[32 48 54 58 93 95 96]
[[89 56 48]
 [98 76 78]]
[[48 56 89]
 [76 78 98]]
[[[85 36]
  [46 32]]

 [[92 81]
  [94 98]]]
[[[36 85]
  [32 46]]

 [[81 92]
  [94 98]]]
[68 90 93 86 45 50]
[93 90 86 68 50 45]
[50 59 90 80 92]
[59 90 80 92]
[[78 80 90]
 [65 29 54]]
[50 59]
[25 85 98 26 20 86]
[25 20]
[[35 78 74]
 [89 70 48]
 [89 91 87]]
[[35 74]
 [89 48]
 [89 87]]
[10 55 75 79 99]
['False' 'True' 'True' 'True' 'True']
[63 76 72 29 90 98 95]
['Grade B' 'Grade A' 'Grade B' 'Grade B' 'Grade A' 'Grade A' 'Grade A']
['prime' 'not prime' 'not prime' 'prime' 'not prime' 'not prime' 'prime']
[ 45  49  52  80  52 100]
[[ 76  56  90]
 [ 88  51   8]
 [ 78 102  98]
 [ 75  35  48]]
[ 69  61  46 100 120]
396
79.2
median: 69.0
max: 120
cumulative [        69       4209     193614   19361400 2323368000]
product 2323368000
range: 74
deviation: 26.962195756280682


Pandas

In [ ]:
import pandas as pd
data = pd.Series([65,78,90])
print(data)

#dict
import pandas as pd
dict = {"Name:":["Shivangi","Siya","Isha","Yash"],"age":[20,19,28,27],"salary":[90000,78000,200000,150000]}
df = pd.DataFrame(data=dict)
print(df)

import pandas as pd
sp = pd.Series([68,256,81])
print(sp)
#
import pandas as pd
d = [16,25,64,81,100]
df = pd.Series(data = d)
print(df)

#
import pandas as pd
d = {"Name":"Shivangi","Age":"20","Roll-no ":93}
df = pd.Series(data = d,index = ["Name","Age","Roll-no"])
print(df)
#
import pandas as pd
dict = { "Name":["Shivangi","Priya","Yashneel","Isha","Aarav"],"Roll-no":[20,19,28,26,24]}
df = pd.DataFrame(data = dict)
print(df)

#
import pandas as pd
data = {"Emp_ID":[101,102,103,104,105,106],
        "Name":["Amit","Riya","Raj","Sara","John","Neha"],
        "Department":["IT","HR","Finance","IT","Sales","HR"],
        "Salary":[50000,45000,60000,55000,48000,52000],
        "Experience":[2,3,5,4,1,3]}
df = pd.DataFrame(data)
print(df.head(1))
print(df.head(-3))
print(df.tail(4))
print(df.tail(-2))
print(df.shape)
df.rename(columns={"Emp_ID":"Emp ID","Name":"E_Name"},inplace=True)
print(df.describe())
df.info()
print(df)

#
import pandas as pd
dict = {"name":["Shivangi","Vishal","Raju"],
        "salary":[90000,45000,55000]}
df = pd.DataFrame(data = dict)
df["marks"]= [30,70,66]
df["increment"] = df["salary"] + (df["salary"] / 20)
print(df)



0    65
1    78
2    90
dtype: int64
      Name:  age  salary
0  Shivangi   20   90000
1      Siya   19   78000
2      Isha   28  200000
3      Yash   27  150000
0     68
1    256
2     81
dtype: int64
0     16
1     25
2     64
3     81
4    100
dtype: int64
Name       Shivangi
Age              20
Roll-no         NaN
dtype: object
       Name  Roll-no
0  Shivangi       20
1     Priya       19
2  Yashneel       28
3      Isha       26
4     Aarav       24
   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
   Emp_ID  Name Department  Salary  Experience
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Departm

In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/imspandey2006-lgtm/grras-tasks/main/student-data-.json"
df = pd.read_json(url)
print(df)
male_students = df[df['gender'] =='Male']
print(male_students)
female_students = df[df['gender'] =='Female']
print(female_students)
print(df.iloc[0:8])
print(df.loc[0:6])
print(df.loc[0,"name"])
print(df.iloc[3])
print(df.loc[2])
df["total"] = df["physics"]+(df["maths"]) + (df["english"])
print(df)
print(df[df["maths"]>56])
print(df[df["physics"] <= 78])
print(df[df["english"]==78])

# to apply multiple filter
print(df[(df["maths"] >= 88) & (df["physics"] > 89)])
print(df[(df["maths"] >= 88) & (df["physics"] > 89) & (df["gender"]=="Male")]["name"])

# to sort values - by default-ascending
#print(df.sort_values("maths"))
df.sort_values("maths",ascending=False, inplace=True)
print(df)
df.sort_values(by =['english'],ascending=[False])
print(df)
#
#print(df.sort_values("name"))
# a to z
df['name'] = df['name'].str.lower()
print(df.sort_values("name"))
# to add row
df ["total"] = df["physics"]+(df["maths"]) + (df["english"])
print(df)
df.loc[14]=["shivangi",'Female',86,90,98,274]
print(df)
print(df.drop("total",axis = 1))
df.drop ([13],axis=0,inplace=True)
print(df)
print(df.drop([7,8,9,10,11,12,14]))
##
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df['dob'] = ['2005-02-14','2008-09-04','2004-03-06','2006-09-10','2004-10-05']
print(df)
print(df['dob'].dtype)
#
df['dob'] = pd.to_datetime(df['dob'])
print(df)
print(df['dob'].dt.year)
print(df['dob'].dt.month)
print(df['dob'].dt.day)
print(df['dob'].dt.day_name())
print(df)
#30 days
print(df['dob'] + pd.to_timedelta(30,unit='D'))
print(df['dob'] + pd.to_timedelta('30 days'))
print(df)


       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
       name gender  physics  maths  english
0      arun   Male       88     87       78
1    rajesh   Male       96    100       95
2   moorthy   Male       89     90       70
3      raja   Male       30     25       40
6    Sundar   Male       12     67       67
8    Dinesh   Male       56     45       67
11      Ram   Mal

In [14]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df.loc[4,'marks']= None
df.loc[3,'roll no']= None
df.isnull()

#sum
df.isnull().sum()

#drop null val
#by row
df.dropna()

#by col
df.dropna(axis=1)

#fill by
df.fillna(0)
df.fillna(100)

df['roll no'] ==df['roll no'].fillna(200)
df.fillna({'roll no': 200, 'marks': 100})

df
df['marks'].mean
df.fillna({'marks':df['marks'].mean()})

#


,name,roll no,marks
0,dheeraj,123.0,10.000000
1,kunal,NaN,20.000000
2,abhishek,12345.0,23.333333
3,praveen,NaN,40.000000
4,anjali,1234567.0,23.333333


Aggregation function

In [15]:
#aggregation & group by
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df['marks'].sum()
df['marks'].mean()
df['marks'].max()
df['marks'].count()
df['marks'].agg(["sum","mean","max","count"])



,marks
sum,120.0
mean,30.0
max,50.0
count,4.0


In [16]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df1 = pd.read_json(url)
#pd.concat([df,df1]) # by default row
df1.loc[2,"name"] = "Shivangi"
print(pd.concat([df,df1],axis = 1))


       name    roll no  marks      name    roll no  marks
0   dheeraj      123.0   10.0   dheeraj      123.0   10.0
1     kunal        NaN   20.0     kunal        NaN   20.0
2  abhishek    12345.0    NaN  Shivangi    12345.0    NaN
3   praveen    12356.0   40.0   praveen    12356.0   40.0
4    anjali  1234567.0   50.0    anjali  1234567.0   50.0
